before_script:
  - chmod -c 755 scripts/*
  - chmod -c 755 tests/*

tests:
  script:
    - ./tests/tests-runner.sh ./tests/hajmdal.tests.sh ./scripts/hajmdal.sh
  artifacts:
    paths:
      - ./tests-results/*